name: CI - Build

on:
  push:
    branches: [stag]


jobs:
  build:
    name: 'build and push'
    environment: stag
    runs-on: ubuntu-latest

    steps:
      - uses:  actions/checkout@v4

      - name: Print environment 
        id: print_environment
        env:
          RAIL_DB: ${{ vars.RAIL_DB }}  
        run: |
          echo "Print variable $RAIL_DB"
